--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

-- Started on 2024-11-06 19:26:31

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 17371)
-- Name: authors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authors (
    id integer NOT NULL,
    name character varying(512),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE public.authors OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 24158)
-- Name: cart_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cart_items (
    id integer NOT NULL,
    cart_id integer NOT NULL,
    product_id integer NOT NULL,
    price double precision,
    quantity integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE public.cart_items OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 24157)
-- Name: cart_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 24151)
-- Name: carts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.carts (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE public.carts OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 24427)
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id integer NOT NULL,
    title character varying(55) NOT NULL,
    level integer NOT NULL,
    url_key character varying(51),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 17386)
-- Name: categories_depend; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories_depend (
    category_id integer NOT NULL,
    level integer,
    level_1_id integer,
    level_2_id integer,
    level_3_id integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE public.categories_depend OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 24190)
-- Name: order_details; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_details (
    id integer NOT NULL,
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    price double precision,
    quantity integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE public.order_details OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 24189)
-- Name: order_details_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 24183)
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    id integer NOT NULL,
    user_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 24182)
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 17380)
-- Name: product_authors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_authors (
    product_id integer,
    id integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE public.product_authors OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 24142)
-- Name: product_categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_categories (
    product_id integer,
    category_id integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE public.product_categories OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 17423)
-- Name: product_descriptions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_descriptions (
    id integer NOT NULL,
    description character varying(65579),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE public.product_descriptions OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 24067)
-- Name: product_highlights; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_highlights (
    product_id integer NOT NULL,
    name character varying(189) NOT NULL,
    title character varying(16) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE public.product_highlights OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 17391)
-- Name: product_images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_images (
    id integer NOT NULL,
    image_url character varying(181) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE public.product_images OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 17411)
-- Name: product_infos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_infos (
    id integer NOT NULL,
    name character varying(295) NOT NULL,
    url_key character varying(669),
    short_url character varying(54) NOT NULL,
    short_description character varying(203),
    original_price integer NOT NULL,
    thumbnail_url character varying(195),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE public.product_infos OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 24145)
-- Name: product_inventory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_inventory (
    product_id integer NOT NULL,
    quantity integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE public.product_inventory OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 24123)
-- Name: product_options; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_options (
    product_id integer NOT NULL,
    code character varying(14) NOT NULL,
    name character varying(71),
    label character varying(91),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE public.product_options OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 17395)
-- Name: product_seller; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_seller (
    product_id integer NOT NULL,
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE public.product_seller OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 24071)
-- Name: product_specifications_attrs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_specifications_attrs (
    product_id integer NOT NULL,
    name character varying(61) NOT NULL,
    code character varying(32) NOT NULL,
    value character varying(11193),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE public.product_specifications_attrs OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 24174)
-- Name: review_medias; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.review_medias (
    id integer NOT NULL,
    review_id integer NOT NULL,
    url character varying,
    type_media character varying,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE public.review_medias OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 24173)
-- Name: review_medias_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.review_medias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_medias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 24165)
-- Name: reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reviews (
    id integer NOT NULL,
    product_id integer NOT NULL,
    user_id integer NOT NULL,
    rating integer,
    comment character varying,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE public.reviews OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 24164)
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 17398)
-- Name: sellers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sellers (
    id integer NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.sellers OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 24196)
-- Name: shipments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shipments (
    id integer NOT NULL,
    status character varying,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone
);


ALTER TABLE public.shipments OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 17219)
-- Name: users_account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_account (
    id integer NOT NULL,
    full_name character varying,
    username character varying,
    avatar_url character varying,
    address character varying,
    district character varying,
    province character varying,
    day_of_birth timestamp with time zone,
    gender character varying(6),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone
);


ALTER TABLE public.users_account OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 17205)
-- Name: users_login_data; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_login_data (
    id integer NOT NULL,
    phone character varying NOT NULL,
    email character varying NOT NULL,
    password_hash character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone
);


ALTER TABLE public.users_login_data OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 17204)
-- Name: users_login_data_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_login_data_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_login_data_id_seq OWNER TO postgres;

--
-- TOC entry 5011 (class 0 OID 0)
-- Dependencies: 216
-- Name: users_login_data_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.users_login_data_id_seq OWNED BY public.users_login_data.id;


--
-- TOC entry 4761 (class 2604 OID 17208)
-- Name: users_login_data id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_login_data ALTER COLUMN id SET DEFAULT nextval('public.users_login_data_id_seq'::regclass);


--
-- TOC entry 4790 (class 2606 OID 17377)
-- Name: authors authors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authors
    ADD CONSTRAINT authors_pkey PRIMARY KEY (id);


--
-- TOC entry 4802 (class 2606 OID 24163)
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);


--
-- TOC entry 4800 (class 2606 OID 24156)
-- Name: carts carts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (id);


--
-- TOC entry 4814 (class 2606 OID 24431)
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- TOC entry 4810 (class 2606 OID 24195)
-- Name: order_details order_details_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT order_details_pkey PRIMARY KEY (id);


--
-- TOC entry 4808 (class 2606 OID 24188)
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- TOC entry 4796 (class 2606 OID 17429)
-- Name: product_descriptions product_descriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_descriptions
    ADD CONSTRAINT product_descriptions_pkey PRIMARY KEY (id);


--
-- TOC entry 4794 (class 2606 OID 17417)
-- Name: product_infos product_infos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_infos
    ADD CONSTRAINT product_infos_pkey PRIMARY KEY (id);


--
-- TOC entry 4798 (class 2606 OID 24150)
-- Name: product_inventory product_inventory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_inventory
    ADD CONSTRAINT product_inventory_pkey PRIMARY KEY (product_id);


--
-- TOC entry 4806 (class 2606 OID 24181)
-- Name: review_medias review_medias_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review_medias
    ADD CONSTRAINT review_medias_pkey PRIMARY KEY (id);


--
-- TOC entry 4804 (class 2606 OID 24172)
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- TOC entry 4792 (class 2606 OID 17402)
-- Name: sellers sellers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sellers
    ADD CONSTRAINT sellers_pkey PRIMARY KEY (id);


--
-- TOC entry 4812 (class 2606 OID 24203)
-- Name: shipments shipments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shipments
    ADD CONSTRAINT shipments_pkey PRIMARY KEY (id);


--
-- TOC entry 4788 (class 2606 OID 17226)
-- Name: users_account users_account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_account
    ADD CONSTRAINT users_account_pkey PRIMARY KEY (id);


--
-- TOC entry 4785 (class 2606 OID 17213)
-- Name: users_login_data users_login_data_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_login_data
    ADD CONSTRAINT users_login_data_pkey PRIMARY KEY (id);


--
-- TOC entry 4786 (class 1259 OID 17232)
-- Name: ix_users_account_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_users_account_id ON public.users_account USING btree (id);


ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES public.carts(id);

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product_infos(id);

ALTER TABLE ONLY public.categories_depend
    ADD CONSTRAINT categories_depend_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id);

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT order_details_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id);

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT order_details_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product_infos(id);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users_account(id);

ALTER TABLE ONLY public.product_authors
    ADD CONSTRAINT product_authors_id_fkey FOREIGN KEY (id) REFERENCES public.authors(id);

ALTER TABLE ONLY public.product_authors
    ADD CONSTRAINT product_authors_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product_infos(id);

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT product_categories_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id);

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT product_categories_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product_infos(id);

ALTER TABLE ONLY public.product_descriptions
    ADD CONSTRAINT product_descriptions_id_fkey FOREIGN KEY (id) REFERENCES public.product_infos(id);

ALTER TABLE ONLY public.product_highlights
    ADD CONSTRAINT product_highlights_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product_infos(id);

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT product_images_id_fkey FOREIGN KEY (id) REFERENCES public.product_infos(id);

ALTER TABLE ONLY public.product_infos
    ADD CONSTRAINT product_infos_id_fkey FOREIGN KEY (id) REFERENCES public.product_inventory(product_id);

ALTER TABLE ONLY public.product_options
    ADD CONSTRAINT product_options_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product_infos(id);

ALTER TABLE ONLY public.product_seller
    ADD CONSTRAINT product_seller_id_fkey FOREIGN KEY (id) REFERENCES public.sellers(id);

ALTER TABLE ONLY public.product_seller
    ADD CONSTRAINT product_seller_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product_infos(id);

ALTER TABLE ONLY public.product_specifications_attrs
    ADD CONSTRAINT product_specifications_attrs_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product_infos(id);

ALTER TABLE ONLY public.review_medias
    ADD CONSTRAINT review_medias_review_id_fkey FOREIGN KEY (review_id) REFERENCES public.reviews(id);

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product_infos(id);
